"""Step 0: check the environment, then build what the later steps need.

Checks (and prints what is missing instead of failing late): uv, numpy, the two disc images (read in
place, never copied), the Rust tool, free disk space, network access to Overpass. Then creates
dataset/ and runs steps 1 and 2 (disc tables, OSM downloads) unless --check-only.

    uv run --with numpy python examples/05_osm_vs_disc_modugno/00_setup.py [--check-only] [--force] [--clean]

--clean   deletes dataset/ (everything in it is regenerated by the scripts; the OSM downloads are
          the only part that needs the network, so --clean keeps osm_*.json.gz unless --all is given)
--all     with --clean: delete the OSM downloads too
--force   passed to steps 1 and 2 (rebuild what exists)
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import DATA, DISCS, ENDPOINTS, HERE, REPO, RUST

NEED_FREE_GB = 2.0


def check() -> list[str]:
    problems = []
    print("environment")
    if shutil.which("uv"):
        print("  uv: ok")
    else:
        problems.append("uv not found: https://docs.astral.sh/uv/ (or use any Python >= 3.9 with numpy)")
    try:
        import numpy
        print(f"  numpy {numpy.__version__}: ok")
    except ImportError:
        problems.append("numpy missing: run with `uv run --with numpy python ...`")
    for disc, path in DISCS.items():
        if path.is_file() and path.stat().st_size > 1 << 20:
            print(f"  disc {disc}: {path.resolve()} ({path.stat().st_size / 1e9:.1f} GB, read in place)")
        else:
            problems.append(f"disc {disc} not readable at {path}: point the symlink {path.relative_to(REPO)} at your copy "
                            f"of the image (ln -sf /path/to/image {path})")
    if RUST.exists():
        print(f"  Rust tool: {RUST.relative_to(REPO)}: ok")
    else:
        problems.append("Rust tool missing: (cd carindb-rs && cargo build --release) -- only needed for whole-disc passes (dump-type, xref)")
    free = shutil.disk_usage(REPO).free / 1e9
    if free >= NEED_FREE_GB:
        print(f"  free disk: {free:.0f} GB (the study needs well under 0.5 GB)")
    else:
        problems.append(f"only {free:.1f} GB free; the study needs under 0.5 GB but keep some room")
    r = subprocess.run(["curl", "-s", "-m", "20", "-o", "/dev/null", "-w", "%{http_code}", "-A", "opencarin-research/0.1",
                        ENDPOINTS[0].replace("interpreter", "status")], capture_output=True, text=True)
    if r.stdout.strip() == "200":
        print("  Overpass (overpass-api.de): reachable")
    else:
        problems.append(f"Overpass not reachable (HTTP {r.stdout.strip() or r.returncode}): step 2 will retry; downloads already in dataset/ are reused")
    return problems


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check-only", action="store_true")
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--clean", action="store_true")
    ap.add_argument("--all", action="store_true")
    a = ap.parse_args()
    if a.clean:
        n = 0
        for p in DATA.glob("*") if DATA.exists() else []:
            if p.name.startswith("osm_") and not a.all:
                continue
            p.unlink() if p.is_file() else shutil.rmtree(p)
            n += 1
        print(f"deleted {n} files from {DATA.relative_to(REPO)}" + ("" if a.all else " (OSM downloads kept; --all deletes them)"))
        return
    problems = check()
    if problems:
        print("\nmissing or doubtful:")
        for p in problems:
            print("  -", p)
    DATA.mkdir(exist_ok=True)
    if a.check_only:
        return
    fatal = any(p.startswith(("disc", "numpy")) for p in problems)
    if fatal:
        raise SystemExit("\nfix the items above (discs, numpy) and rerun")
    flag = ["--force"] if a.force else []
    for step in ("01_extract_disc.py", "02_fetch_osm.py"):
        print(f"\n== {step}")
        subprocess.run([sys.executable, str(HERE / step), *flag], check=False)
    size = sum(p.stat().st_size for p in DATA.glob("*") if p.is_file())
    print(f"\ndataset/: {size / 1e6:.0f} MB. Next: 03_match.py, then the numbered analyses.")


if __name__ == "__main__":
    main()
